### ISSUE TITLE
After Sandbox upgrade there are difficulties with deployment

### ISSUE THREAD

**Issue by Stepan007** [amtrack/force-dev-tool#117]
After Sandbox upgrade there are difficulties with deployment of profiles. Very often there are some new features which have to be removed manually when deploying to a Sandbox with lower version (before upgrade).

**Comment by amtrack** [comment]
Hi @Stepan007 ,

i don't think this is related to force-dev-tool.
It is a general issue with Salesforce and Metadata.

If you want to process Metadata (a.k.a. "remove features") in order to deploy in between orgs of different API versions, you might try https://github.com/IPfolioDev/metadata-xml-tool
