### ISSUE TITLE
PermissinSet sync

### ISSUE THREAD

**Issue by vkolotov** [amtrack/force-dev-tool#89]
Hi @amtrack,

I'm trying to set up a CI environment which deploys changes from git to salesforce. I've got some bash scripts which generate changesets and then deploy them to salesforce. However, I came across an issue with PermissionSet metadata. When I try to deploy incremental changes which include some changes in PermissionSets, I get this:

```
Error: Deployment with RunSpecifiedTests option failed.
 - Error in PermissionSet component 'Bulk_Send_Notifications': Required field is missing: label
```

I've started to troubleshoot and noticed that force-dev-tool generates some files under config/deployments/<changesetname>/permissionsets. For some strange reason the files under permissionsets folder are not the same as in "src" folder, e.g. they contain only a fraction of data (presumably just changes):

Bulk_Send_Notifications.permissionset file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<PermissionSet xmlns="http://soap.sforce.com/2006/04/metadata">
    <fieldPermissions>
      <editable>false</editable>
      <field>CITestObject__c.TestField__c</field>
      <readable>false</readable>
    </fieldPermissions>
</PermissionSet>
```

Whereas its counterpart under src folder is a lot bigger, it also includes ```<label>``` tag as well. 

So the question is, why does force-dev-tool not just copy files from src to changeset folder? How to make force-dev-tool to copy entire files? I would assume that if you deploy a changeset you should have a FULL file which you have imported from salesforce, otherwise if you deploy just a part of that file, salesforce will remove/delete missing parts in the org.

Thanks,
Vlad

**Comment by amtrack** [comment]
Hi @vkolotov,
thanks for reporting!
You are right, the `label` element is missing indeed.
According to the [documentation](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_permissionset.htm) the label is required.
I thought that `PermissionSet` can be treated the same way as `Profile` which was a wrong assumption.
I will provide a fix once i figured out a good solution.

However i disagree on the approach to deploy a FULL file.
To understand my point of view, i suggest you create a Changeset in the Salesforce Setup Interface yourself, add a `Permission Set` together with a `Visualforce Page` (for example).
If you upload the Changeset to another org and click on `View Source` for the Permission Set you'll see that only elements of the Permission Set itself (such as `label`), the `userPermissions` elements and further **only** elements of components you included in the Changeset (here `pageAccesses` for the Visualforce Page) will be contained in the file.

Salesforce usually doesn't delete anything due to absence.
You'll have to specify a `destructiveChanges.xml` file in the deployment to delete something, see [here](https://developer.salesforce.com/docs/atlas.en-us.daas.meta/daas/daas_destructive_changes.htm).

However if you still want to deploy the full PermissionSet, you can create a changeset with `force-dev-tool` the following way:

```console
$ force-dev-tool changeset create my-permission-set PermissionSet/MyPermissionSet
```

Again, thanks for reporting, and i'm happy to see more issues being reported like this!

**Comment by amtrack** [comment]
Hi @vkolotov,
thanks for reporting!
You are right, the `label` element is missing indeed.
According to the [documentation](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_permissionset.htm) the label is required.
I thought that `PermissionSet` can be treated the same way as `Profile` which was a wrong assumption.
I will provide a fix once i figured out a good solution.

However i disagree on the approach to deploy a FULL file.
To understand my point of view, i suggest you create a Changeset in the Salesforce Setup Interface yourself, add a `Permission Set` together with a `Visualforce Page` (for example).
If you upload the Changeset to another org and click on `View Source` for the Permission Set you'll see that only elements of the Permission Set itself (such as `label`), the `userPermissions` elements and further **only** elements of components you included in the Changeset (here `pageAccesses` for the Visualforce Page) will be contained in the file.

Salesforce usually doesn't delete anything due to absence.
You'll have to specify a `destructiveChanges.xml` file in the deployment to delete something, see [here](https://developer.salesforce.com/docs/atlas.en-us.daas.meta/daas/daas_destructive_changes.htm).

However if you still want to deploy the full PermissionSet, you can create a changeset with `force-dev-tool` the following way:

```console
$ force-dev-tool changeset create my-permission-set PermissionSet/MyPermissionSet
```

Again, thanks for reporting, and i'm happy to see more issues being reported like this!

**Comment by vkolotov** [comment]
Hi @amtrack, sounds good. Looking forward to seeing the fix.

**Comment by okram999** [comment]
@amtrack this is really a show stopper :(  ... is there a quick fix for this, we cannot remove the permissionsets from the git-diff  and thus, it fails the deployment

**Comment by okram999** [comment]
Not sure how you are handling this? But i am trying to get some python script in between to replace the content of the permissionsets folder from the actual src folder, once the force-dev-tool generates the src and the package xml in the config folder. The script will replace the files under the config's src/permissionset with the ones from the main src folder... but it will have the full permissionset files

**Comment by froucher** [comment]
Hello, I want to ask if someone is working in a solution for this bug. If not, I will try to investigate if I can create a pull request, but not sure if I will be able...

**Comment by amtrack** [comment]
@froucher I'm looking into it now.

**Comment by froucher** [comment]
:clap::clap::clap:
